version: "3"
services:
  db-dev:
    container_name: postgres-dev
    image: postgres
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=restaurateur
    ports:
      - '5435:5432'
    volumes:
      - ../postgres-data-dev:/var/lib/postgresql/data
      - ./backend/restaurants.sql:/docker-entrypoint-initdb.d/create_tables.sql
  frontend-dev:
    container_name: frontend-dev
    build:
      context: ./frontend
      args:
        - HTTP_PROXY=backend-dev
    ports:
      - '3030:3000'
  backend-dev:
    container_name: backend-dev
    build:
      context: ./backend
    environment:
      - DB_DSN=postgresql://$DB_USER:$DB_PASS@postgres-dev/restaurateur?sslmode=disable
    ports:
      - '8085:8080'
