version: "3"
services:
  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=restaurateur
    ports:
      - '5432:5432'
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
      - ./backend/restaurants.sql:/docker-entrypoint-initdb.d/create_tables.sql
  app:
    build:
      context: .
      args:
        - REACT_APP_PROXY=https://api.restaurateur.tech
    container_name: app
    depends_on:
      - db
    environment:
      - DB_DSN=postgresql://$DB_USER:$DB_PASS@postgres/restaurateur?sslmode=disable
      - ORIGIN_ALLOWED=https://restaurateur.tech
    ports:
      - '3000:3000'
      - '8080:8080'
