name: backend

on:
  push:
    paths: backend/**
  pull_request:
    paths: backend/**
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2

      - name: Go setup
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.2'

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
          go get github.com/PuerkitoBio/goquery@v1.6.1

      - name: Build
        run: go build .

      - name: Lint check
        run: golint ./...

      - name: Vet check
        run: go vet ./...

      - name: Format check
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: Run tests
        run: go test ./...
