name: deploy

on:
  release:
    types: [released]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEP_PATH: /home/${{ secrets.SSH_USER }}/restaurateur/
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOST }}
      - name: Deploy Testing
        shell: bash
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ env.DEP_PATH }}; sudo docker-compose -p restaurateur-dev -f docker-compose-dev.yml down"
          rsync -avz . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ env.DEP_PATH }}
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ env.DEP_PATH }}; sudo docker-compose -p restaurateur-dev -f docker-compose-dev.yml up --build  -d"
