name: frontend

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events
  push:
    paths: frontend/**
    branches: [ main, release-0.2**, release-0.3** ]
  pull_request:
    paths: frontend/**
    branches: [ main, release-0.2**, release-0.3**]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test
      - name: Generate build
        run: npm run build
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-build
          path: frontend/build
 
