name: gosec2

on:
  push:
    paths: backend/**
  pull_request:
    paths: backend/**
    branches: [ main ]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2

      - name: Go setup
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.2'

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Build
        run: go build .
        
  tests:
    needs: [build]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        
      - name: missing-import
        run:  go get github.com/PuerkitoBio/goquery
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: -exclude G107 ./...
